# $GITHUB_WORKSPACE/src -> this project files
# $GITHUB_WORKSPACE/grpc -> proto files
# $GITHUB_WORKSPACE/tools -> tools for code generation
name: Update Source Code
on: [push]
jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out project files
        uses: actions/checkout@v1
        with:
          path: src
      - name: Check out proto files
        uses: actions/checkout@v1
        with:
          repository: QuorumEngineering/quorum-plugin-definitions
          ref: refs/heads/simple
          token: ${{ secrets.QUORUMBOT_PAT }}
          path: grpc
      - name: Install tools
        run: |
          mkdir -p ../tools && cd ../tools
          curl -q -L https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip -o protoc.zip && unzip -q protoc.zip
          ./bin/protoc --version
          export GOPATH=$(pwd)
          go get github.com/golang/protobuf/protoc-gen-go
          go get github.com/golang/mock/mockgen
          go get golang.org/x/tools/cmd/goimports
          ls -lha ./bin
      - name: Generate code
        run: |
          export PATH=$PATH:../tools/bin/ && mkdir -p grpc/proto && mkdir -p grpc/mock_proto
          protoc -I ../grpc -I ../grpc/vendor --go_out=plugins=grpc:grpc/proto ../grpc/init.proto ../grpc/helloworld.proto ../grpc/security.proto
          export GOPATH=$(pwd)/..
          mockgen -package mock_proto -destination grpc/mock_proto/mock_initializer.go -source grpc/proto/init.pb.go
          mockgen -package mock_proto -destination grpc/mock_proto/mock_helloworld.go  -source grpc/proto/helloworld.pb.go
          mockgen -package mock_proto -destination grpc/mock_proto/mock_security.go    -source grpc/proto/security.pb.go
          ls -lha grpc/proto
          git add -A
          git status
      - name: Commit changes
        run: |
          git config --local user.name "Trung Nguyen"
          git config --local user.email "24930+trung@users.noreply.github.com"
          (git commit -am "Auto update" && echo 0) || echo 1
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
     #- name: Push changes
     #   uses: ad-m/github-push-action@master
     #   with:
     #     github_token: ${{ secrets.QUORUMBOT_PAT }}
