name: extract-owner
on:
  push:
    branches:
      - master
jobs:
  trigger:
    name: Trigger quorum-security-plugin-sdk-go generation
    runs-on: ubuntu-latest
    steps:
      - name: Extract repository owner
        run: |
          repo=${{ github.repository }}
          owner=${repo%/*}
          echo "::set-env name=REPO_OWNER::$owner"
      - name: Output owner
        run: |
          echo "${{ env.REPO_OWNER }}"
