name: Test
on:
  push:
    tags:
        - 'v*'  
    branches:
      - master
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup jfrog CLI'
        uses: jfrog/setup-jfrog-cli@v1
      - name: 'try to use jfrog'
        run: |
          jfrog --version
