name: Test
on:
  pull_request:
  push:
    tags:
        - 'v*'  
    branches:
      - master
jobs:
  job1:
    name: Github Context
    runs-on: ubuntu-latest
    steps:
      - name: 'Print Github Context'
        run: |
          echo ${{ toJson(github) }}
