name: Trigger
on:
  push:
    paths:
    - README.md
jobs:
  trigger:
    name: Fire webhook event
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.QUORUMBOT_PAT }}
        event-type: proto-files-updated
        client-payload: '{"repo": "${{ github.repository }}", "sha": "${{ github.sha }}"}'